(()=>{
const d=document,$=id=>d.getElementById(id);
const sec=$('registrations');
if(sec){
  sec.querySelectorAll('h2').forEach(h=>{if(h.textContent.includes('Regola U12')){const list=h.parentElement.querySelector('.list');if(list)list.innerHTML='<div class="list-row"><span>Partecipazione U12</span><span class="pill green">GRATUITA</span></div><div class="list-row"><span>Prima maglia U12</span><span class="pill orange">€20</span></div><div class="list-row"><span>Ogni maglia extra</span><span class="pill orange">+€20</span></div><div class="list-row"><span>Over U12</span><span class="pill blue">€50 · 1 inclusa</span></div>';}});
}
const shirt=$('rShirt');
if(shirt&&!$('rExtra')){
  const section=shirt.closest('.drawer-section');
  const rule=$('rRule');
  rule.insertAdjacentHTML('beforebegin','<div class="form-grid section-gap"><div class="field"><label>MAGLIE EXTRA</label><input id="rExtra" type="number" min="0" max="10" value="0"></div><div class="field"><label>TAGLIA EXTRA</label><select id="rExtraSize"><option>Nessuna</option><option>XS</option><option>S</option><option>M</option><option>L</option><option>XL</option><option>XXL</option></select></div></div>');
  const recalc=()=>{
    const u12=$('rCat').value==='U12',first=$('rShirt').checked,extras=Math.max(0,parseInt($('rExtra').value||'0',10));
    let total=u12?((first?20:0)+extras*20):(50+extras*20);
    if(!u12)$('rShirt').checked=true;
    $('rAmount').value='€'+total;
    if(total===0){$('rPay').value='Non richiesto';$('rSize').value='Nessuna';$('rRule').className='payment-rule';$('rRule').innerHTML='<b>U12 gratuito.</b><br>Nessuna maglia richiesta.'}
    else{if($('rPay').value==='Non richiesto')$('rPay').value='Da pagare';$('rRule').className='payment-rule warning';$('rRule').innerHTML=u12?'<b>U12 gratuito.</b><br>Prima maglia €20, ogni maglia extra +€20.':'<b>Quota Over U12 €50.</b><br>Una maglia inclusa, ogni maglia extra +€20.'}
    $('rExtraSize').disabled=extras===0;if(extras===0)$('rExtraSize').value='Nessuna';
  };
  ['rCat','rShirt'].forEach(id=>$(id).addEventListener('change',()=>setTimeout(recalc,0)));
  $('rExtra').addEventListener('input',recalc);
  d.querySelectorAll('.reg-open').forEach(b=>b.addEventListener('click',()=>{setTimeout(()=>{$('rExtra').value='0';$('rExtraSize').value='Nessuna';recalc()},0)}));
}
const players=$('players');
if(players){
players.innerHTML=`<div class="topbar"><div><span class="eyebrow">PLAYER DATABASE</span><h1>Giocatori</h1><div class="muted">Profili permanenti, storico eventi, valutazioni e documenti.</div></div><div class="actions"><button class="btn secondary">Importa</button><button class="btn primary">+ Nuovo giocatore</button></div></div>
<div class="grid4"><article class="card stat"><span>GIOCATORI TOTALI</span><strong>286</strong><small>34 nuovi questo mese</small></article><article class="card stat"><span>PROFILI COMPLETI</span><strong>214</strong><small>74,8%</small></article><article class="card stat"><span>DA APPROVARE</span><strong>12</strong><small>Richiedono revisione</small></article><article class="card stat"><span>DOCUMENTI SCADUTI</span><strong>9</strong><small>Da aggiornare</small></article></div>
<div class="card section-gap"><div class="toolbar"><input class="input search" id="playerSearch" placeholder="Cerca nome, anno, squadra o città"><select class="select" id="playerCat"><option value="">Tutte le categorie</option><option>U12</option><option>U14</option><option>U16</option><option>U18</option><option>U19</option></select><select class="select" id="playerStatus"><option value="">Tutti gli stati</option><option>Completo</option><option>Da approvare</option></select></div><div class="table-wrap"><table id="playersTable"><thead><tr><th>GIOCATORE</th><th>ANNO</th><th>RUOLO</th><th>SQUADRA</th><th>EVENTI</th><th>VALUTAZIONE</th><th>PROFILO</th><th></th></tr></thead><tbody>
<tr data-search="david panopio 2010 roma" data-cat="U16" data-status="Completo"><td><div class="person"><div class="avatar">DP</div><div><b>David Panopio</b><div class="muted">Roma</div></div></div></td><td>2010</td><td>PG</td><td>Roma</td><td>3</td><td><span class="pill blue">85/100</span></td><td><span class="pill green">Completo</span></td><td><button class="btn small secondary player-open" data-player="david">Scheda</button></td></tr>
<tr data-search="dwayne vivero 2007 roma fil italia" data-cat="U19" data-status="Completo"><td><div class="person"><div class="avatar">DV</div><div><b>Dwayne Vivero</b><div class="muted">Roma</div></div></div></td><td>2007</td><td>SG</td><td>FIL-ITALIA</td><td>5</td><td><span class="pill blue">91/100</span></td><td><span class="pill green">Completo</span></td><td><button class="btn small secondary player-open" data-player="dwayne">Scheda</button></td></tr>
<tr data-search="manuel cruz 2012 milano basket" data-cat="U14" data-status="Da approvare"><td><div class="person"><div class="avatar">MC</div><div><b>Manuel Cruz</b><div class="muted">Milano</div></div></div></td><td>2012</td><td>SF</td><td>Milano Basket</td><td>1</td><td><span class="pill orange">73/100</span></td><td><span class="pill orange">Da approvare</span></td><td><button class="btn small secondary player-open" data-player="manuel">Scheda</button></td></tr>
</tbody></table></div><p id="playerEmpty" class="muted" style="display:none;padding:18px;text-align:center">Nessun giocatore trovato.</p></div>`;
const pdata={david:{name:'David Panopio',sub:'U16 · Roma',year:'2010',role:'PG',team:'Roma',height:'178 cm',skill:86,iq:91,def:78,events:['Roma U21 · MVP emergente','Roma Talent ID · Valutato','Italy Final Camp · Convocato'],notes:'Playmaker creativo, ottima lettura del pick and roll.'},dwayne:{name:'Dwayne Vivero',sub:'U19 · Roma',year:'2007',role:'SG',team:'FIL-ITALIA',height:'185 cm',skill:92,iq:87,def:84,events:['Roma U21 · MVP','Italy Final Camp · Selezionato','FIL-ITALIA Travel Team'],notes:'Scorer affidabile, leadership positiva.'},manuel:{name:'Manuel Cruz',sub:'U14 · Milano',year:'2012',role:'SF',team:'Milano Basket',height:'170 cm',skill:74,iq:70,def:76,events:['Milano Talent ID · Registrato'],notes:'Profilo nuovo. Verificare documenti e contatto genitore.'}};
d.body.insertAdjacentHTML('beforeend',`<div class="drawer-backdrop" id="pBack"></div><aside class="reg-drawer" id="pDrawer"><div class="drawer-head"><div><span class="eyebrow" style="color:#9bc9b2">PLAYER PROFILE</span><h2 id="pName"></h2><div class="muted" id="pSub"></div></div><button class="drawer-close" id="pClose">×</button></div><div class="drawer-body"><section class="drawer-section"><h3>Profilo</h3><div class="form-grid"><div class="field"><label>ANNO</label><input id="pYear"></div><div class="field"><label>RUOLO</label><input id="pRole"></div><div class="field"><label>SQUADRA</label><input id="pTeam"></div><div class="field"><label>ALTEZZA</label><input id="pHeight"></div></div></section><section class="drawer-section"><h3>Stato</h3><div class="chip-row"><span class="pill green">Profilo verificato</span><span class="pill blue">Eleggibile FIL</span><span class="pill orange">Documenti controllati</span></div></section><section class="drawer-section"><h3>Storico eventi</h3><div class="list" id="pEvents"></div></section><section class="drawer-section"><h3>Valutazione</h3><div class="drawer-summary"><div><span>SKILL</span><b id="pSkill"></b></div><div><span>IQ</span><b id="pIq"></b></div><div><span>DIFESA</span><b id="pDef"></b></div></div><div class="field section-gap"><label>NOTE INTERNE</label><textarea id="pNotes" rows="4"></textarea></div></section><section class="drawer-section"><div class="drawer-actions"><button class="btn primary wide" id="pSave">Salva profilo</button><button class="btn secondary">Iscrivi a evento</button><button class="btn secondary">Invia email</button><button class="btn danger-btn">Archivia</button></div></section></div></aside>`);
const drawer=$('pDrawer'),back=$('pBack');
d.querySelectorAll('.player-open').forEach(b=>b.addEventListener('click',()=>{const x=pdata[b.dataset.player];$('pName').textContent=x.name;$('pSub').textContent=x.sub;$('pYear').value=x.year;$('pRole').value=x.role;$('pTeam').value=x.team;$('pHeight').value=x.height;$('pSkill').textContent=x.skill;$('pIq').textContent=x.iq;$('pDef').textContent=x.def;$('pEvents').innerHTML=x.events.map(e=>'<div class="list-row"><span>'+e+'</span><span class="pill blue">Apri</span></div>').join('');$('pNotes').value=x.notes;drawer.classList.add('show');back.classList.add('show')}));
const close=()=>{drawer.classList.remove('show');back.classList.remove('show')};$('pClose').onclick=close;back.onclick=close;$('pSave').onclick=()=>{if(window.showToast)window.showToast('Profilo giocatore salvato nella demo.')};
const filter=()=>{const q=$('playerSearch').value.toLowerCase(),cat=$('playerCat').value,status=$('playerStatus').value;let n=0;d.querySelectorAll('#playersTable tbody tr').forEach(r=>{const ok=(!q||r.dataset.search.includes(q))&&(!cat||r.dataset.cat===cat)&&(!status||r.dataset.status===status);r.style.display=ok?'':'none';if(ok)n++});$('playerEmpty').style.display=n?'none':'block'};$('playerSearch').oninput=filter;$('playerCat').onchange=filter;$('playerStatus').onchange=filter;
}
})();