const playersData = [
  {
    id: "mico-miguel-manliclic",
    name: "Mico Miguel Manliclic",
    year: "2007",
    category: "U19",
    role: "2007 • Point Guard",
    position: "2007 • Point Guard",
    height: "175 cm",
    club: "Giants Marghera",
    city: "Venice, Italy",
    nationality: "Filipino / Italian",
    jerseyNumber: "",
    instagram: "",
    handedness: "",
    image: "images/players/6.jpg",
    cardImage: "images/players/5.jpg",
    highlights: "#",
    imagePosition: "center top",
    status: "Active"
  },

  {
    id: "christian-patrick-landicho",
    name: "Christian Patrick Landicho",
    year: "2007",
    category: "U19",
    role: "2007 • Point Guard",
    position: "2007 • Point Guard",
    height: "175 cm",
    club: "Roma Basketball Academy",
    city: "Rome, Italy",
    nationality: "Filipino / Italian",
    jerseyNumber: "",
    instagram: "",
    handedness: "",
    image: "images/players/4.jpg",
    cardImage: "images/players/3.jpg",
    highlights: "#",
    imagePosition: "center top",
    status: "Active"
  },

  {
    id: "brian-matthew-rosales",
    name: "Brian Matthew Rosales",
    year: "2009",
    category: "U17",
    role: "2009 • Shooting Guard",
    position: "2009 • Shooting Guard",
    height: "184 cm",
    club: "BSL - Basket Save My Life",
    city: "Bologna, Italy",
    nationality: "Filipino / Italian",
    jerseyNumber: "",
    instagram: "",
    handedness: "",
    image: "images/players/2.jpg",
    cardImage: "images/players/1.jpg",
    highlights: "#",
    imagePosition: "center top",
    status: "Active"
  },

  {
    id: "alexander-james-gatpandan",
    name: "Alexander James Gatpandan",
    year: "2009",
    category: "U19",
    role: "2009 • Guard / Small Forward",
    position: "2009 • Guard / Small Forward",
    height: "185 cm",
    club: "Stella EBK",
    city: "Rome, Italy",
    nationality: "Filipino / Italian",
    jerseyNumber: "",
    instagram: "",
    handedness: "",
    image: "images/players/8.jpg",
    cardImage: "images/players/7.jpg",
    highlights: "#",
    imagePosition: "center top",
    status: "Active"
  }
];
