const playersData = [
  {
    name: "Mico Miguel Manliclic",
    year: "2007",
    roleKey: "playerRole1",
    bioKey: "playerBio1",
    cardRoleKey: "playerCardRole1",
    cardRoleText: "2007 • Point Guard",
    height: "175 cm",
    category: "U19",
    club: "Giants Marghera",
    city: "Venice, Italy",
    nationality: "Filipino / Italian",
    highlights: "#",
    cardImage: "images/players/5.jpg",
    image: "images/players/6.jpg"
  },
  {
    name: "Christian Patrick Landicho",
    year: "2007",
    roleKey: "playerRole2",
    bioKey: "playerBio2",
    cardRoleKey: "playerCardRole2",
    cardRoleText: "2007 • Point Guard",
    height: "175 cm",
    category: "U19",
    club: "Roma Basketball Academy",
    city: "Rome, Italy",
    nationality: "Filipino / Italian",
    highlights: "#",
    cardImage: "images/players/3.jpg",
    image: "images/players/4.jpg"
  },
  {
    name: "Brian Matthew Rosales",
    year: "2009",
    roleKey: "playerRole3",
    bioKey: "playerBio3",
    cardRoleKey: "playerCardRole3",
    cardRoleText: "2009 • Shooting Guard",
    height: "184 cm",
    category: "U17",
    club: "BSL - Basket Save My Life",
    city: "Bologna, Italy",
    nationality: "Filipino / Italian",
    highlights: "#",
    cardImage: "images/players/1.jpg",
    image: "images/players/2.jpg"
  },
  {
    name: "Alexander James Gatpandan",
    year: "2009",
    roleKey: "Guard / Small Forward",
    bioKey: "playerBio4",
    cardRoleKey: "playerCardRole4",
    cardRoleText: "2009 • Guard / Small Forward",
    height: "185 cm",
    category: "U19",
    club: "Stella EBK",
    city: "Rome, Italy",
    nationality: "Filipino / Italian",
    highlights: "#",
    cardImage: "images/players/7.jpg",
    image: "images/players/8.jpg"
  }
];
